//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesSearch.WebApplication.BuilderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuildersState", Namespace="http://schemas.datacontract.org/2004/07/RecipesSearch.Data.Views")]
    [System.SerializableAttribute()]
    public partial struct BuildersState : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllTasksBuildInProgressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IdfBuildFailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IdfBuildInProgressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SimilarResultsBuildFailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SimilarResultsPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SimilarResultsUpdateInProgressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SimilarResultsUpdatedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TfBuildFailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TfBuildInProgressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TfBuildProgressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TfIdfBuildFailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TfIdfBuildInProgressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TfIdfBuildProgressField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllTasksBuildInProgress {
            get {
                return this.AllTasksBuildInProgressField;
            }
            set {
                if ((this.AllTasksBuildInProgressField.Equals(value) != true)) {
                    this.AllTasksBuildInProgressField = value;
                    this.RaisePropertyChanged("AllTasksBuildInProgress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IdfBuildFailed {
            get {
                return this.IdfBuildFailedField;
            }
            set {
                if ((this.IdfBuildFailedField.Equals(value) != true)) {
                    this.IdfBuildFailedField = value;
                    this.RaisePropertyChanged("IdfBuildFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IdfBuildInProgress {
            get {
                return this.IdfBuildInProgressField;
            }
            set {
                if ((this.IdfBuildInProgressField.Equals(value) != true)) {
                    this.IdfBuildInProgressField = value;
                    this.RaisePropertyChanged("IdfBuildInProgress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SimilarResultsBuildFailed {
            get {
                return this.SimilarResultsBuildFailedField;
            }
            set {
                if ((this.SimilarResultsBuildFailedField.Equals(value) != true)) {
                    this.SimilarResultsBuildFailedField = value;
                    this.RaisePropertyChanged("SimilarResultsBuildFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SimilarResultsPercentage {
            get {
                return this.SimilarResultsPercentageField;
            }
            set {
                if ((this.SimilarResultsPercentageField.Equals(value) != true)) {
                    this.SimilarResultsPercentageField = value;
                    this.RaisePropertyChanged("SimilarResultsPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SimilarResultsUpdateInProgress {
            get {
                return this.SimilarResultsUpdateInProgressField;
            }
            set {
                if ((this.SimilarResultsUpdateInProgressField.Equals(value) != true)) {
                    this.SimilarResultsUpdateInProgressField = value;
                    this.RaisePropertyChanged("SimilarResultsUpdateInProgress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SimilarResultsUpdatedCount {
            get {
                return this.SimilarResultsUpdatedCountField;
            }
            set {
                if ((this.SimilarResultsUpdatedCountField.Equals(value) != true)) {
                    this.SimilarResultsUpdatedCountField = value;
                    this.RaisePropertyChanged("SimilarResultsUpdatedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TfBuildFailed {
            get {
                return this.TfBuildFailedField;
            }
            set {
                if ((this.TfBuildFailedField.Equals(value) != true)) {
                    this.TfBuildFailedField = value;
                    this.RaisePropertyChanged("TfBuildFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TfBuildInProgress {
            get {
                return this.TfBuildInProgressField;
            }
            set {
                if ((this.TfBuildInProgressField.Equals(value) != true)) {
                    this.TfBuildInProgressField = value;
                    this.RaisePropertyChanged("TfBuildInProgress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TfBuildProgress {
            get {
                return this.TfBuildProgressField;
            }
            set {
                if ((this.TfBuildProgressField.Equals(value) != true)) {
                    this.TfBuildProgressField = value;
                    this.RaisePropertyChanged("TfBuildProgress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TfIdfBuildFailed {
            get {
                return this.TfIdfBuildFailedField;
            }
            set {
                if ((this.TfIdfBuildFailedField.Equals(value) != true)) {
                    this.TfIdfBuildFailedField = value;
                    this.RaisePropertyChanged("TfIdfBuildFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TfIdfBuildInProgress {
            get {
                return this.TfIdfBuildInProgressField;
            }
            set {
                if ((this.TfIdfBuildInProgressField.Equals(value) != true)) {
                    this.TfIdfBuildInProgressField = value;
                    this.RaisePropertyChanged("TfIdfBuildInProgress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TfIdfBuildProgress {
            get {
                return this.TfIdfBuildProgressField;
            }
            set {
                if ((this.TfIdfBuildProgressField.Equals(value) != true)) {
                    this.TfIdfBuildProgressField = value;
                    this.RaisePropertyChanged("TfIdfBuildProgress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BuilderService.IBuilderService")]
    public interface IBuilderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildTf", ReplyAction="http://tempuri.org/IBuilderService/BuildTfResponse")]
        void BuildTf();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildTf", ReplyAction="http://tempuri.org/IBuilderService/BuildTfResponse")]
        System.Threading.Tasks.Task BuildTfAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/StopTfBuild", ReplyAction="http://tempuri.org/IBuilderService/StopTfBuildResponse")]
        void StopTfBuild();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/StopTfBuild", ReplyAction="http://tempuri.org/IBuilderService/StopTfBuildResponse")]
        System.Threading.Tasks.Task StopTfBuildAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildTfIdf", ReplyAction="http://tempuri.org/IBuilderService/BuildTfIdfResponse")]
        void BuildTfIdf();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildTfIdf", ReplyAction="http://tempuri.org/IBuilderService/BuildTfIdfResponse")]
        System.Threading.Tasks.Task BuildTfIdfAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/StopTfIdfBuild", ReplyAction="http://tempuri.org/IBuilderService/StopTfIdfBuildResponse")]
        void StopTfIdfBuild();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/StopTfIdfBuild", ReplyAction="http://tempuri.org/IBuilderService/StopTfIdfBuildResponse")]
        System.Threading.Tasks.Task StopTfIdfBuildAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildIdf", ReplyAction="http://tempuri.org/IBuilderService/BuildIdfResponse")]
        void BuildIdf();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildIdf", ReplyAction="http://tempuri.org/IBuilderService/BuildIdfResponse")]
        System.Threading.Tasks.Task BuildIdfAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildSimilarResults", ReplyAction="http://tempuri.org/IBuilderService/BuildSimilarResultsResponse")]
        void BuildSimilarResults(int resultsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildSimilarResults", ReplyAction="http://tempuri.org/IBuilderService/BuildSimilarResultsResponse")]
        System.Threading.Tasks.Task BuildSimilarResultsAsync(int resultsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/StopSimilarResultsBuild", ReplyAction="http://tempuri.org/IBuilderService/StopSimilarResultsBuildResponse")]
        void StopSimilarResultsBuild();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/StopSimilarResultsBuild", ReplyAction="http://tempuri.org/IBuilderService/StopSimilarResultsBuildResponse")]
        System.Threading.Tasks.Task StopSimilarResultsBuildAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildAllTasks", ReplyAction="http://tempuri.org/IBuilderService/BuildAllTasksResponse")]
        void BuildAllTasks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/BuildAllTasks", ReplyAction="http://tempuri.org/IBuilderService/BuildAllTasksResponse")]
        System.Threading.Tasks.Task BuildAllTasksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/StopAllTasksUpdating", ReplyAction="http://tempuri.org/IBuilderService/StopAllTasksUpdatingResponse")]
        void StopAllTasksUpdating();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/StopAllTasksUpdating", ReplyAction="http://tempuri.org/IBuilderService/StopAllTasksUpdatingResponse")]
        System.Threading.Tasks.Task StopAllTasksUpdatingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/GetBuildersState", ReplyAction="http://tempuri.org/IBuilderService/GetBuildersStateResponse")]
        RecipesSearch.WebApplication.BuilderService.BuildersState GetBuildersState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuilderService/GetBuildersState", ReplyAction="http://tempuri.org/IBuilderService/GetBuildersStateResponse")]
        System.Threading.Tasks.Task<RecipesSearch.WebApplication.BuilderService.BuildersState> GetBuildersStateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuilderServiceChannel : RecipesSearch.WebApplication.BuilderService.IBuilderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuilderServiceClient : System.ServiceModel.ClientBase<RecipesSearch.WebApplication.BuilderService.IBuilderService>, RecipesSearch.WebApplication.BuilderService.IBuilderService {
        
        public BuilderServiceClient() {
        }
        
        public BuilderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuilderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuilderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuilderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void BuildTf() {
            base.Channel.BuildTf();
        }
        
        public System.Threading.Tasks.Task BuildTfAsync() {
            return base.Channel.BuildTfAsync();
        }
        
        public void StopTfBuild() {
            base.Channel.StopTfBuild();
        }
        
        public System.Threading.Tasks.Task StopTfBuildAsync() {
            return base.Channel.StopTfBuildAsync();
        }
        
        public void BuildTfIdf() {
            base.Channel.BuildTfIdf();
        }
        
        public System.Threading.Tasks.Task BuildTfIdfAsync() {
            return base.Channel.BuildTfIdfAsync();
        }
        
        public void StopTfIdfBuild() {
            base.Channel.StopTfIdfBuild();
        }
        
        public System.Threading.Tasks.Task StopTfIdfBuildAsync() {
            return base.Channel.StopTfIdfBuildAsync();
        }
        
        public void BuildIdf() {
            base.Channel.BuildIdf();
        }
        
        public System.Threading.Tasks.Task BuildIdfAsync() {
            return base.Channel.BuildIdfAsync();
        }
        
        public void BuildSimilarResults(int resultsCount) {
            base.Channel.BuildSimilarResults(resultsCount);
        }
        
        public System.Threading.Tasks.Task BuildSimilarResultsAsync(int resultsCount) {
            return base.Channel.BuildSimilarResultsAsync(resultsCount);
        }
        
        public void StopSimilarResultsBuild() {
            base.Channel.StopSimilarResultsBuild();
        }
        
        public System.Threading.Tasks.Task StopSimilarResultsBuildAsync() {
            return base.Channel.StopSimilarResultsBuildAsync();
        }
        
        public void BuildAllTasks() {
            base.Channel.BuildAllTasks();
        }
        
        public System.Threading.Tasks.Task BuildAllTasksAsync() {
            return base.Channel.BuildAllTasksAsync();
        }
        
        public void StopAllTasksUpdating() {
            base.Channel.StopAllTasksUpdating();
        }
        
        public System.Threading.Tasks.Task StopAllTasksUpdatingAsync() {
            return base.Channel.StopAllTasksUpdatingAsync();
        }
        
        public RecipesSearch.WebApplication.BuilderService.BuildersState GetBuildersState() {
            return base.Channel.GetBuildersState();
        }
        
        public System.Threading.Tasks.Task<RecipesSearch.WebApplication.BuilderService.BuildersState> GetBuildersStateAsync() {
            return base.Channel.GetBuildersStateAsync();
        }
    }
}
