// <auto-generated />
namespace RecipesSearch.DAL.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddedKeywordProcessingSettingForCrawlerConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedKeywordProcessingSettingForCrawlerConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201502151208522_AddedKeywordProcessingSettingForCrawlerConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
